config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    collection do
      get :search_in_companies_house
    end
  end
  root 'companies#search_in_companies_house'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validate :not_blank

  def to_s
    %i[address_line_1 address_line_2 locality country postal_code].map{|f| self[f].presence}.compact.join(', ')
  end

  def not_blank
    %i[address_line_1 address_line_2 locality country postal_code].any?(&:present?)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  self.inheritance_column = 'sti_type'
  belongs_to :address, optional: true
  accepts_nested_attributes_for :address, reject_if: :all_blank

  validates :company_name, presence: true
  validates_uniqueness_of :company_number, message: '- a company with this number is already saved'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all.order(:company_name).preload(:address).paginate(page: params[:page], per_page: 100).to_a
  end

  # Search companies using Companies House UK service
  def search_in_companies_house
    if params.has_key?(:term)
      term = params[:term]
      if term.blank?
        flash.now[:error] = 'Please enter a valid search term'
      else
        results = CompaniesHouse.search_company(term)
        if results[:error]
          flash.now[:error] = "Error while searching (#{results[:error]})."
        else
          @results = results
        end
      end
    end
  end

  def destroy
    c = Company.find_by(id: params[:id])
    if c&.destroy
      flash[:notice] = 'Deleted'
    else
      flash[:error] = 'Could not delete company'
    end
    redirect_to action: :index
  end

  def create
    company = Company.new(company_params)
    if company.save
      flash[:notice] = 'Saved'
    else
      flash[:error] = "Could not save company (#{company.errors.full_messages.join('; ')})"
    end
    redirect_to action: :index
  end

  def update
    company = Company.find_by(id: params[:id])
    if company
      updated_company_data = CompaniesHouse.get_company_by_number(company.company_number)
      if updated_company_data[:error]
        flash[:error] = "Error getting company information (#{updated_company_data[:error]})"
      else
        attrs = updated_company_data[:company].attributes.select{|_,v| v.present?}
        attrs[:address_attributes] = updated_company_data[:company].address.attributes.select{|_,v| v.present?}
        if company.update(attrs)
          flash[:notice] = "Data for company with number #{company.company_number} updated"
        else
          flash[:error] = "Error updating company information (#{company.errors.full_messages.join('; ')})"
        end
      end
    else
      flash[:error] = "Could not find company with id #{params[:id]}"
    end
    redirect_to action: :index
  end

  private

  def company_params
    params.require(:company).permit(:company_number, :company_name, :date_of_creation, :type, :jurisdiction, :company_status, address_attributes: [:address_line_1, :address_line_2, :locality, :country, :postal_code])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_companies_field_tds.html.haml
%td= c.company_number
%td= c.company_name
%td= c.company_status&.titleize
%td= c.date_of_creation
%td= c.type&.humanize&.titleize
%td= c.jurisdiction&.gsub('-', ' / ')&.titleize
%td= c.address&.to_s

app/views/companies/_companies_field_ths.html.haml
%th Number
%th Name
%th Status
%th Date Of Creation
%th Type
%th Jurisdiction
%th Address
%th

app/views/companies/index.html.haml
%p
  These are the companies saved from the search results of Companies House UK.
  = link_to 'Search for a company in Companies House UK', search_in_companies_house_companies_path
= will_paginate @companies
%table
  %thead
    %tr
      = render partial: 'companies/companies_field_ths'
  %tbody
    - @companies.each do |c|
      %tr
        = render partial: 'companies/companies_field_tds', locals: {c: c}
        %td
          = button_to 'Delete', {action: "destroy", id: c.id}, method: :delete, data: { confirm: "Are you sure?" }
          = button_to 'Update', {action: "update", id: c.id}, method: :patch
- if @companies.count == 0
  .alert.alert-info{role: 'alert'}
    There are currently no companies saved in My Yellow Book

app/views/companies/search_in_companies_house.html.haml
%h2 Search companies using Companies House UK service
= link_to 'View saved companies in My Yellow Book', companies_path
= form_tag search_in_companies_house_companies_path, autocomplete: :off, method: :get do
  .field
    %label{for: :term} Search term:
    = text_field_tag :term, params[:term]
    = submit_tag 'Go'

- if @results
  %h3<
    Found #{pluralize(@results[:total_results], 'record')}
    - if @results[:total_results] > @results[:items_per_page]
      %span.normal= ", #{@results[:items_per_page]} displayed"

  %table#c-s-results
    %thead
      %tr
        = render partial: 'companies/companies_field_ths'
    %tbody
      - @results[:companies].each do |c|
        %tr
          = render partial: 'companies/companies_field_tds', locals: {c: c}
          - c_attrs = c.attributes.select{|_,v| v.present?}
          - c_attrs[:address_attributes] = c.address.attributes.select{|_,v| v.present?}
          %td= button_to 'Save', {action: "create", company: c_attrs}, method: :post

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyYellowBook
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %h1 My Yellow Book
    #content
      - flash.each do |name, msg|
        - if msg.present?
          %div{class: "alert alert-#{name.to_s == 'error' ? 'danger' : 'success'} alert-dismissible", role: 'alert'}
            %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
              %span{'aria-hidden' => 'true'} &times;
            - if msg.kind_of?(Array)
              - msg.each do |item|
                %h3= raw(item)
            - else
              %h3= raw(msg)
      = yield
    %footer= "Copyright &copy; #{DateTime.now.year} MyYellowBook.".html_safe